   name: compile-driver

   on:
     push:
       branches: [ main, gh-actions-test, cache ]
     pull_request:
       branches: [ main, gh-actions-test, cache ]

   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: cache linux
        id: cache-linux
        uses: actions/cache@v3
        env:
          cache-name: cache-linux-kernel
        with:
          path: ./linux
          key: ${{ runner.os }}

      - name: checkout linux
        if: ${{ steps.cache-linux.outputs.cache-hit != 'true' }}
        uses: actions/checkout@v3
        with:
          repository: torvalds/linux
          path: ./linux
          ref:  v6.0

      - name: install libelf-dev
        if: ${{ steps.cache-linux.outputs.cache-hit != 'true' }}
        run: |
          sudo apt-get update
          sudo apt-get install libelf-dev

      - name: prepare linux
        if: ${{ steps.cache-linux.outputs.cache-hit != 'true' }}
        working-directory: ./linux
        run: |
          make x86_64_defconfig
          make modules_prepare

      - name: compile driver
        run: make -C ./linux M=$PWD modules
